# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0003_auto_20170605_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '선생')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='teacher_attrs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='introduction_to_models.Person', verbose_name='선생님'),
        ),
    ]
