# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0009_remove_tradeinfo_date_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinfo',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
